### ISSUE TITLE
Error in model based measures

### ISSUE THREAD

**Issue by moisesrsantos** [FelSiq/ts-pymfe#2]
Hello,
When import "tsmfe" I have found this error:

File "-/experiment.py", line 2, in <module>
    import pymfe.tsmfe
  File "-\site-packages\pymfe\tsmfe.py", line 10, in <module>
    import pymfe._internal as _internal
  File "-\site-packages\pymfe\_internal.py", line 86, in <module>
    import pymfe.model_based as model_based
  File "-\site-packages\pymfe\model_based.py", line 18, in <module>
    class MFETSModelBased:
  File "-\site-packages\pymfe\model_based.py", line 299, in MFETSModelBased
    ) -> statsmodels.tsa.holtwinters.results.HoltWintersResultsWrapper:
AttributeError: module 'statsmodels.tsa.holtwinters' has no attribute 'results'

**Comment by FelSiq** [comment]
Hi @moisesrsantos,

could you please send me your ts-pymfe version (`pip list | egrep 'tspymfe'`) and statsmodels version (`pip list | egrep 'statsmodels'`)?

I've released a ts-pymfe new version (0.0.4) yesterday. Maybe updating (`pip install -U tspymfe`) resolves this issue?

Also, note that issue seems more related to the statsmodels version itself. The package currently supports the `statsmodels 0.12.2 version`, which is the most recent release. Maybe just updating it also resolves the issue. Could you please check this out?

**Comment by moisesrsantos** [comment]
Hi @FelSiq,
Thank you for to fast answer. I update the statsmodels to 0.12.2 version and the package worked normally.
